### ISSUE TITLE
Create language guide

### ISSUE THREAD

**Issue by willsoto** [Coefficient/style-guide#1]
Need to have a cohesive language guide

**Comment by willsoto** [comment]
ping @skyler, @tom-coefficient  

These are some good starting points:
1. [MailChimp's Language Guide](http://voiceandtone.com/)
2. [GitHub's Language Guide](https://github.com/styleguide/words)

**Comment by skyler** [comment]
I like to consider myself a pretty good copywriter, so I'm going to
copypasta some styleguides together, maybe with a few edits, and use that
as a base which we can all contribute to and shape as we go.

On Tue, Jan 28, 2014 at 9:03 AM, Will Soto notifications@github.com wrote:

> ping @skyler https://github.com/skyler, @tom-coefficienthttps://github.com/tom-coefficient
> 
> These are some good starting points:
> 1. MailChimp's Language Guide http://voiceandtone.com/
> 2. GitHub's Language Guide https://github.com/styleguide/words
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Coefficient/style-guide/issues/1#issuecomment-33480263
> .

## 

Skyler
